/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/arutselvan15/estore-product-kube-client/pkg/apis/estore/v1"
	scheme "github.com/arutselvan15/estore-product-kube-client/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProductsGetter has a method to return a ProductInterface.
// A group's client should implement this interface.
type ProductsGetter interface {
	Products(namespace string) ProductInterface
}

// ProductInterface has methods to work with Product resources.
type ProductInterface interface {
	Create(*v1.Product) (*v1.Product, error)
	Update(*v1.Product) (*v1.Product, error)
	UpdateStatus(*v1.Product) (*v1.Product, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Product, error)
	List(opts metav1.ListOptions) (*v1.ProductList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Product, err error)
	ProductExpansion
}

// products implements ProductInterface
type products struct {
	client rest.Interface
	ns     string
}

// newProducts returns a Products
func newProducts(c *EstoreV1Client, namespace string) *products {
	return &products{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the product, and returns the corresponding product object, and an error if there is any.
func (c *products) Get(name string, options metav1.GetOptions) (result *v1.Product, err error) {
	result = &v1.Product{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("products").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Products that match those selectors.
func (c *products) List(opts metav1.ListOptions) (result *v1.ProductList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ProductList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("products").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested products.
func (c *products) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("products").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a product and creates it.  Returns the server's representation of the product, and an error, if there is any.
func (c *products) Create(product *v1.Product) (result *v1.Product, err error) {
	result = &v1.Product{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("products").
		Body(product).
		Do().
		Into(result)
	return
}

// Update takes the representation of a product and updates it. Returns the server's representation of the product, and an error, if there is any.
func (c *products) Update(product *v1.Product) (result *v1.Product, err error) {
	result = &v1.Product{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("products").
		Name(product.Name).
		Body(product).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *products) UpdateStatus(product *v1.Product) (result *v1.Product, err error) {
	result = &v1.Product{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("products").
		Name(product.Name).
		SubResource("status").
		Body(product).
		Do().
		Into(result)
	return
}

// Delete takes name of the product and deletes it. Returns an error if one occurs.
func (c *products) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("products").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *products) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("products").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched product.
func (c *products) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Product, err error) {
	result = &v1.Product{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("products").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
